plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.protobuf)
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
}

protobuf {
    protoc {
        artifact = libs.protoc.get()
    }

    generateProtoTasks {
        all().configureEach { task ->
            task.builtins {
                remove("java")
                java {}
            }
        }
    }
}

android {
    compileSdk COMPILE_SDK.toInteger()

    defaultConfig {
        applicationId "com.android.settings"
        minSdk MIN_SDK_VERSION.toInteger()
        targetSdk TARGET_SDK_VERSION.toInteger()
        versionCode 33
        versionName "13"
        vectorDrawables.useSupportLibrary = true
    }

    signingConfigs {
        platform {
            storeFile file("platform.keystore")
            storePassword '123456'
            keyAlias 'platform'
            keyPassword '123456'
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled false
            signingConfig signingConfigs.platform
        }

        debug {
            debuggable true
            minifyEnabled false
            signingConfig signingConfigs.platform
        }

        applicationVariants.all { variant ->
            variant.outputs.all {
                outputFileName = "Settings.apk"
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            proto.srcDirs = ['protos']
            manifest.srcFile 'AndroidManifest.xml'
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    compileOnly files('libs/framework.jar')
    compileOnly files('libs/core-all.jar')
    compileOnly files('libs/telephony-common.jar')
    compileOnly files('libs/ims-common.jar')
    compileOnly files('libs/app-compat-annotations.jar')

    implementation files('libs/zxing-core-1.7.jar')
    implementation files('libs/android.hidl.base-V1.0-java.jar')
    implementation files('libs/android.hardware.dumpstate-V1.0-java.jar')
    implementation files('libs/android.hardware.dumpstate-V1.1-java.jar')
    implementation files('libs/settings-logtags.jar')
    implementation files('libs/statslog-settings.jar')
    implementation files('libs/core-icu4j.jar')

    implementation project(':WifiTrackerLib')
    implementation project(':setupcompat')
    implementation project(':setupdesign')
    implementation project(':iconloaderlib')
    implementation project(':SettingsLib')
    implementation project(':SettingsLib:ActionBarShadow')
    implementation project(':SettingsLib:RestrictedLockUtils')
    implementation project(':SettingsLib:ActionButtonsPreference')
    implementation project(':SettingsLib:HelpUtils')
    implementation project(':SettingsLib:SettingsSpinner')
    implementation project(':SettingsLib:Tile')
    implementation project(':SettingsLib:LayoutPreference')
    implementation project(':SettingsLib:AppPreference')
    implementation project(':SettingsLib:RadioButtonPreference')
    implementation project(':SettingsLib:search')
    implementation project(':SettingsLib:SearchWidget')
    implementation project(':SettingsLib:EntityHeaderWidgets')
    implementation project(':SettingsLib:AdaptiveIcon')
    implementation project(':SettingsLib:DisplayDensityUtils')
    implementation project(':SettingsLib:IllustrationPreference')
    implementation project(':SettingsLib:SettingsTransition')
    implementation project(':SettingsLib:MainSwitchPreference')
    implementation project(':SettingsLib:TwoTargetPreference')
    implementation project(':SettingsLib:FooterPreference')
    implementation project(':SettingsLib:BannerMessagePreference')
    implementation project(':SettingsLib:TopIntroPreference')
    implementation project(':SettingsLib:UsageProgressBarPreference')
    implementation project(':SettingsLib:CollapsingToolbarBaseActivity')
    implementation project(':SettingsLib:EmergencyNumber')
    implementation project(':SettingsLib:ButtonPreference')
    implementation project(':SettingsLib:SelectorWithWidgetPreference')
    implementation project(':SettingsLib:Utils')
    implementation project(':SettingsLib:ActivityEmbedding')

    implementation(':preference-1.2.0-alpha01@aar')
    implementation(':contextualcards@aar')

    implementation libs.appcompat
    implementation libs.recyclerview
    implementation libs.slice.builders
    implementation libs.slice.core
    implementation libs.slice.view
    implementation libs.constraintlayout
    implementation libs.cardview
    implementation libs.material
    implementation libs.lifecycle.runtime
    implementation libs.lifecycle.extensions
    implementation libs.protobuf.java
    implementation libs.protoc
    implementation libs.lottie
    implementation libs.guava
    implementation libs.window
}

allprojects {
    tasks.withType(JavaCompile).configureEach { task ->
        task.doFirst {
            def originalClasspath = options.bootstrapClasspath ?: files()
            options.bootstrapClasspath = files(
                    file("${rootDir}/libs/framework.jar"),
                    file("${rootDir}/libs/core-all.jar")
            ).plus(originalClasspath)
        }
    }
}